### ISSUE TITLE
[Request] MQTT entity "is ready" / backlog of commands

### ISSUE THREAD

**Issue by raphmur** [tesla-local-control/tesla-local-control-addon#28]
We can spam the MQTT buttons as frequently as we want and then the loop will progressively process the mqtt messages...

My automation has wait times of 30 sec after each button press, but sometimes (ex. lower than 5a charge request) it is not sufficient and the mqtt messages start accumulating over time.

I see three options:
- Set an "MQTT purge" button, that allows purging all the messages on hold for a specific entity. Note that the command `mosquitto_sub -E -i tesla_ble_mqtt -h $MQTT_IP -p $MQTT_PORT -u $MQTT_USER -P $MQTT_PWD -t tesla_ble/+` does not seem to do the job well... --> EDIT: not sure about this...
- Create a new entity "MQTT ready" which basically tells you if the mqtt pipe is empty...
- Find a way to feedback an attribute to all the MQTT entities which is set to "not available" until the command finishes

What do you think?

**Comment by raphmur** [comment]
In addition, is there a way to show the backlog of messages not yet processed?

**Comment by iainbullock** [comment]
Let me have a think about it. However my initial thought is this.

**If** the BLE presence scanning can be done in a parallel thread (I'm not sure where we are with this; there have been some reports it doesn't work, but maybe it does). We could set QOS to 0 instead of 1, and stop using the durable client session options in mosquitto_sub, and have it time out sing the -W option. 

It would stop listening after the timeout and when the loop restarts any new messages would be dropped

**Comment by raphmur** [comment]
Closing for now. The simple error parsing works.
Will re-open when it becomes too irritating
