### ISSUE TITLE
[Feature] Auto capture MAC from VIN (via calculate BLE LNAME)

### ISSUE THREAD

**Issue by raphmur** [tesla-local-control/tesla-local-control-addon#31]
_See https://github.com/raphmur/tesla-local-control-addon/pull/30#issuecomment-2183554269_

Please see branch cal-ble-mac https://github.com/raphmur/tesla-local-control-addon/tree/cal-ble-mac
Not committed to main yet pending more testing.
@baylanger?

The new code adds steps: 1/ at container init, 2/ every 3 min (in main loop)
What it does: 1/ calculates LNAME from VIN, 2/ Try and find MAC as per https://github.com/iainbullock/tesla_ble_mqtt_docker/issues/10#issuecomment-2180018678 , 3/ If found, export the variable to be accessible in main loop for the listen_to_ble function

/!\ it is not stored in HA config due to 1/ I don't know if this makes sense, 2/ I don't know how to do it.

**Comment by raphmur** [comment]
PR #32

**Comment by epenet** [comment]
Please rename "calculate ble name/discover ble mac"

**Comment by raphmur** [comment]
See https://github.com/tesla-local-control/tesla_ble_mqtt_core/pull/12. Quite a big PR, which includes a major rework by @baylanger on the BLE presence scanning.

**Comment by raphmur** [comment]
Still opened. As of today, we still need to manually provide the vin

**Comment by baylanger** [comment]
> Still opened. As of today, we still need to manually provide the vin
>
With release v0.2.0 later today, the BLE Mac addr isn't a requirement anymore.

The VIN is still required but it's true the logic could use the known BLE Local Name format "S..........C" and automatically use that. There's many approaches we could use to make this easier for the end user... writing whatever pops in my mind, I hope I don't repeat myself :)

1) By default, the logic scans for anything that matches a Tesla car "S.....C" :
- if only 1 car is detected, automatically setup the device using the BLE LN instead of the VIN***
- if more than 1 car detected, setup a device in HA for each of them -> if the end-user ain't the owner of a detected car, he can manually delete those devices. Here the end user needs to figure out his car(s) BLE Local Name to delete the bad entries.

2) By default, the logic scans for anything that matches a Tesla car "S.....C" :
- If only 1 car is detected, automatically setup the device using the BLE LN instead of the VIN***
- If more than 1 car is detected, pick the first one on the list and automatically setup the device. In the device's HA panel "Configuration" card , there could be a "Not owner" button that would add this car in a blocklist and prevent the logic to pick this car in the future. Restarting the add-on would trigger another scan but not pick anything from the blocklist. Here, again, the end user needs to know the BLE LN of his car.

3) If the end-user owns only 1 car and no other Tesla is in the area, setup the device automatically***

4) If the end-user owns only 1 car but more are detected, fail to configure and force the end-user to input a VIN***

5) If the end-user owns 2+ cars, fail to configure and force the end-user to input a VIN***

It is a bit sad Tesla doesn't allow to read the car's name over BLE, the name could be used to setup the device's name instead of -currently- using the VIN - *** if the owner owns 1 car, the name could be set in the config. If own more than 1 car OR if more than 1 car are in the area VIN would be required.... if we want to use the car's name, VIN_LIST could be renamed and allow the following format:
1) single car name (1 car owner, 1 car detected)
2) car name+vin list aka "car_name_one=vin1; car_name_two=vin2" (2+ cars owner, 2+ car detected)

If multiple cars are in the area, the RSSI value could be part of the logic.

This was longer to write than I first thought but a good exercise.
